### ISSUE TITLE
Implement rendering of the Filmography macro

### ISSUE THREAD

**Issue by alansemenov** [enonic/tutorial-react#20]
Will fetch all movies with this actor in the cast and render the list with first image/thumbnail + title of each movie.

The macro has one optional parameter - `heading`, which can be used for setting heading of the movie list. If not provided, "_Filmography_" should be used as a heading.

**Comment by sigdestad** [comment]
List up to 3 movies referencing the person. (using _references property)

**Comment by ComLock** [comment]
Right, so the Macro form is empty then?

**Comment by ComLock** [comment]
Also this task has two parts, one is the Macro xml, which should be in whatever app we go for. 

Then the second part, in this tutorial, which is the GraphQL query, and React implementation.

**Comment by ComLock** [comment]
Alan takes care of the first part
https://github.com/enonic/tutorial-intro/issues/63
